POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
  "name": "Juan de los palotes",
  "username": "juanpalote",
  "email": "juanpalon@april.biz"
}

###
//dara error xq el nombre de usuario es obligatorio
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
  "name": "Juan de los palotes",
  "email": "juanpalon@april.biz"
}
